name: Refresh OneFlow Data
on:
  schedule: [{ cron: "0 */6 * * *" }]
  workflow_dispatch: {}

concurrency:
  group: oneflow-refresh
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build data
        run: |
          mkdir -p data/cloud data/hosting data/tools
          node scripts/fetch-fx.js
          node scripts/fetch-aws.js
          # Optional (turn on when ready)
          # node scripts/fetch-azure.js
          # node scripts/fetch-gcp.js
          # node scripts/fetch-hosting.js
          # node scripts/fetch-tools.js

      - name: List built files (debug)
        run: |
          echo "==== data/ tree ===="
          find data -maxdepth 3 -type f -printf "%p (%k KB)\n" | sort

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.CPANEL_FTP_USER }}
          password: ${{ secrets.CPANEL_FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: data
          server-dir: public_html/oneflow/data
          log-level: verbose
          exclude: |
            **/*.map
            **/.git*
            **/.DS_Store
